- name: Copy client logs after benchmark to monitoring machine
  hosts: bench_clients
  tasks:
    - name: Find files to copy
      find:
        paths: "{{bench_dir}}"
        # Note pattern is as specified in run_worker.sh
        patterns: worker*.out
      register: files_to_copy

    - name: Copy log files
      fetch:
        src: "{{item.path}}"
        dest: "{{bench_dir}}/logs/{{inventory_hostname}}-{{item.path | basename}}"
        flat: yes
      with_items: "{{files_to_copy.files}}"
